### ISSUE TITLE
SyntaxError: Unexpected token, expected "}" (69:18)

### ISSUE THREAD

**Issue by ijgithub** [kavod-io/vscode-jest-test-adapter#127]
When loading the tests within the project, sometimes for some files I get the `SyntaxError: Unexpected token, expected "}" (69:18)` error

What should I do to prevent this error form happening ?

Thanks

**Describe the bug**
- [ ] test load missing suites/tests
- [x] test load errors
- [ ] test running errors

```
[SyntaxError: Unexpected token, expected "}" (69:18)
	at Object._raise (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1411629)
	at Object.raiseWithData (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1411568)
	at Object.raise (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1411396)
	at Object.unexpected (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1431223)
	at Object.expect (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1430983)
	at Object.jsxParseExpressionContainer (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1313642)
	at Object.jsxParseElementAt (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1315282)
	at Object.jsxParseElement (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1315931)
	at Object.parseExprAtom (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1316077)
	at Object.parseExprSubscripts (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1444152)
	at Object.parseMaybeUnary (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1443722)
	at Object.parseMaybeUnary (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1396275)
	at Object.parseExprOps (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1441033)
	at Object.parseMaybeConditional (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1440544)
	at Object.parseMaybeAssign (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1439850)
	at ~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1395231
	at Object.tryParse (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1432079)
	at Object.parseMaybeAssign (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1395211)
	at Object.parseObjectProperty (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1460907)
	at Object.parseObjectProperty (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1309164)
	at Object.parseObjPropValue (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1461414)
	at Object.parseObjPropValue (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1394620)
	at Object.parseObjectMember (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1459776)
	at Object.parseObj (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1458596)
	at Object.parseExprAtom (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1451951)
	at Object.parseExprAtom (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1308521)
	at Object.parseExprAtom (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1316225)
	at Object.parseExprSubscripts (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1444152)
	at Object.parseMaybeUnary (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1443722)
	at Object.parseMaybeUnary (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1396275)
	at Object.parseExprOps (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1441033)
	at Object.parseMaybeConditional (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1440544)
	at Object.parseMaybeAssign (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1439850)
	at Object.parseMaybeAssign (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1395440)
	at Object.parseVar (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1483003)
	at Object.parseVarStatement (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1479527)
	at Object.parseStatementContent (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1472337)
	at Object.parseStatementContent (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1391159)
	at Object.parseStatement (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1471284)
	at Object.parseBlockOrModuleBlockBody (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1481504)
	at Object.parseBlockBody (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1481262)
	at Object.parseBlockBody (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1307804)
	at Object.parseBlock (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1480975)
	at Object.parseStatementContent (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1472482)
	at Object.parseStatementContent (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1391159)
	at Object.parseStatement (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1471284)
	at Object.parseBlockOrModuleBlockBody (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1481504)
	at Object.parseBlockBody (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1481262)
	at Object.parseBlockBody (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1307804)
	at Object.parseBlock (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1480975)
	at Object.parseFunctionBody (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1463364)
	at Object.parseFunctionBody (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1308673)
	at Object.parseFunctionBodyAndFinish (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1463001)
	at Object.parseFunctionBodyAndFinish (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1387816)
	at ~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1484055
	at Object.withTopicForbiddingContext (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1469048)
	at Object.parseFunction (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1484017)
	at Object.parseFunctionStatement (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1477328)
	at Object.parseStatementContent (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1473289)
	at Object.parseStatementContent (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1391159)
	at Object.parseStatement (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1471284)
	at Object.parseBlockOrModuleBlockBody (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1481504)
	at Object.parseBlockBody (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1481262)
	at Object.parseBlockBody (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1307804)
	at Object.parseTopLevel (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1469964)
	at Object.parse (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1498326)
	at Object.t.parse (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:1499898)
	at y (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:2488998)
	at m (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:2489115)
	at t.parseTs (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:2491903)
	at Object.t.default (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:2492172)
	at t.default.parse (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:2844413)
	at t.default.<anonymous> (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:2843893)
	at Generator.next (<anonymous>)
	at s (~/.vscode/extensions/kavod-io.vscode-jest-test-adapter-0.8.1/dist/extension.js:2:2882977)] {
  loc: m { line: 69, column: 18 },
  pos: 1985
}
```

**To Reproduce**
It it difficult to reproduce the error since it does not happen always for every file, but sometimes for some files.

**Desktop (please complete the following information):**
 - OS: Kubuntu 20.04

**Additional context**
I am using the latest version of VS Code v1.57.1

The project is a typescript project. The project uses the following dev dependencies
```
    "@types/jest": "^26.0.23",
    "jest": "^27.0.5",
    "ts-jest": "^27.0.3",
    "ts-node": "^10.0.0",
    "typescript": "^4.3.4"
```

**Comment by ijgithub** [comment]
Please delete this issue. The problem is that the jest-test-adapter does not accept all of the typescript syntax.

I have a case where I am doing typecasting using the following syntax
```
const foo = <ClassNameOfChoice>bar;
```

jest-test-adapter throws the syntax error for this kind of code and fails to recognize tests in the file.

The solution is to use the `as` typecasting syntax.
```
const foo = bar as ClassNameOfChoice;
```
