### ISSUE TITLE
Typescript angle-brackets generate a SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by killergege** [kavod-io/vscode-jest-test-adapter#143]
**Describe the bug**
- [ ] test load missing suites/tests
- [X] test load errors
- [ ] test running errors

When using typescript's angle-brackets syntax in a test, the scan of the test file fails with `SyntaxError: Unexpected token`.

**To Reproduce**
1. Take a typescript project that works (tests scan properly, and run), in my case it is an Angular 13 project, if it matters
2. Use angle-brackets to type an object in one of the tests `const myObject= <MyObject>{ ... };`
3. When scanning for tests, VSCode output for Jest Test Explorer logs are: 
```
[2022-02-01 10:16:38.825] [INFO] Jest Test Explorer activated
[2022-02-01 10:16:38.825] [INFO] Test Explorer found
[2022-02-01 10:16:38.825] [INFO] Creating adapter for c:\Users\MyUser\Documents\Projects\...
[2022-02-01 10:16:38.825] [INFO] Created adapter for workspace: c:\Users\MyUser\Documents\Projects\... with options: {"debugOutput":"internalConsole"}
[2022-02-01 10:16:38.825] [INFO] Registering adapter for c:\Users\MyUser\Documents\Projects\...
[2022-02-01 10:16:38.827] [INFO] Loading Jest tests...
[2022-02-01 10:16:38.828] [INFO] Initialization finished
[2022-02-01 10:16:38.865] [INFO] Selected parser: Nx.dev Angular
[2022-02-01 10:16:38.867] [INFO] Loading Jest settings from c:\Users\MyUser\Documents\Projects\...\jest.config.js...
[2022-02-01 10:16:40.111] [INFO] Force loading all tests...
[2022-02-01 10:16:40.111] [INFO] Loading Jest tests
[2022-02-01 10:16:40.194] [ERROR] [SyntaxError: Unexpected token, expected "}" (36:47)
	at Object._raise (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1411629)
	at Object.raiseWithData (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1411568)
	at Object.raise (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1411396)
	at Object.unexpected (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1431223)
	at Object.expect (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1430983)
	at Object.jsxParseExpressionContainer (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1313642)
	at Object.jsxParseElementAt (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1315282)
	at Object.jsxParseElement (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1315931)
	at Object.parseExprAtom (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1316077)
	at Object.parseExprSubscripts (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1444152)
	at Object.parseMaybeUnary (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1443722)
	at Object.parseMaybeUnary (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1396275)
	at Object.parseExprOps (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1441033)
	at Object.parseMaybeConditional (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1440544)
	at Object.parseMaybeAssign (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1439850)
	at c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1395231
	at Object.tryParse (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1432079)
	at Object.parseMaybeAssign (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1395211)
	at Object.parseVar (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1483003)
	at Object.parseVarStatement (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1479527)
	at Object.parseStatementContent (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1472337)
	at Object.parseStatementContent (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1391159)
	at Object.parseStatement (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1471284)
	at Object.parseBlockOrModuleBlockBody (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1481504)
	at Object.parseBlockBody (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1481262)
	at Object.parseBlockBody (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1307804)
	at Object.parseBlock (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1480975)
	at Object.parseFunctionBody (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1463364)
	at Object.parseFunctionBody (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1308673)
	at Object.parseArrowExpression (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1462700)
	at Object.parseParenAndDistinguishExpression (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1456025)
	at Object.parseExprAtom (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1450790)
	at Object.parseExprAtom (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1308521)
	at Object.parseExprAtom (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1316225)
	at Object.parseExprSubscripts (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1444152)
	at Object.parseMaybeUnary (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1443722)
	at Object.parseMaybeUnary (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1396275)
	at Object.parseExprOps (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1441033)
	at Object.parseMaybeConditional (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1440544)
	at Object.parseMaybeAssign (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1439850)
	at Object.parseMaybeAssign (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1395440)
	at Object.parseExprListItem (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1464714)
	at Object.parseCallExpressionArguments (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1447622)
	at Object.parseSubscript (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1445842)
	at Object.parseSubscript (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1388744)
	at Object.parseSubscripts (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1444472)
	at Object.parseExprSubscripts (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1444230)
	at Object.parseMaybeUnary (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1443722)
	at Object.parseMaybeUnary (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1396275)
	at Object.parseExprOps (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1441033)
	at Object.parseMaybeConditional (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1440544)
	at Object.parseMaybeAssign (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1439850)
	at Object.parseMaybeAssign (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1395440)
	at Object.parseExpression (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1439244)
	at Object.parseStatementContent (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1473353)
	at Object.parseStatementContent (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1391159)
	at Object.parseStatement (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1471284)
	at Object.parseBlockOrModuleBlockBody (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1481504)
	at Object.parseBlockBody (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1481262)
	at Object.parseBlockBody (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1307804)
	at Object.parseBlock (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1480975)
	at Object.parseFunctionBody (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1463364)
	at Object.parseFunctionBody (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1308673)
	at Object.parseArrowExpression (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1462700)
	at Object.parseParenAndDistinguishExpression (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1456025)
	at Object.parseExprAtom (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1450790)
	at Object.parseExprAtom (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1308521)
	at Object.parseExprAtom (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1316225)
	at Object.parseExprSubscripts (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1444152)
	at Object.parseMaybeUnary (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1443722)
	at Object.parseMaybeUnary (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1396275)
	at Object.parseExprOps (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1441033)
	at Object.parseMaybeConditional (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1440544)
	at Object.parseMaybeAssign (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1439850)
	at Object.parseMaybeAssign (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1395440)
	at Object.parseExprListItem (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1464714)
	at Object.parseCallExpressionArguments (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1447622)
	at Object.parseSubscript (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1445842)
	at Object.parseSubscript (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1388744)
	at Object.parseSubscripts (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1444472)
	at Object.parseExprSubscripts (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1444230)
	at Object.parseMaybeUnary (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1443722)
	at Object.parseMaybeUnary (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1396275)
	at Object.parseExprOps (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1441033)
	at Object.parseMaybeConditional (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1440544)
	at Object.parseMaybeAssign (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1439850)
	at Object.parseMaybeAssign (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1395440)
	at Object.parseExpression (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1439244)
	at Object.parseStatementContent (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1473353)
	at Object.parseStatementContent (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1391159)
	at Object.parseStatement (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1471284)
	at Object.parseBlockOrModuleBlockBody (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1481504)
	at Object.parseBlockBody (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1481262)
	at Object.parseBlockBody (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1307804)
	at Object.parseTopLevel (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1469964)
	at Object.parse (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1498326)
	at Object.t.parse (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:1499898)
	at y (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:2488998)
	at m (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:2489115)
	at t.parseTs (c:\Users\MyUser\.vscode\extensions\kavod-io.vscode-jest-test-adapter-0.8.1\dist\extension.js:2:2491903)] {
  loc: m { line: 36, column: 47 },
  pos: 1361
```
And the "Testing" panel in VSCode don't display the tests that are in the file that contains the angle-bracket.
Other tests are displayed properly.

**Expected behavior**
All tests are scanned properly and displayed in the VSCode test panel

**Workaround**
Use the "as" syntax instead of angle-brackets. `const myObject= { ... } as MyObject;` 

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Angular 13, NPM 8.1.2, Node 16.13, Typescript 4.4.3

**Comment by moenchj** [comment]
Same problem here, but the workaroud is not working for me.
OS: AlmaLinux9
Additional context: NodeJS application, Typescript: 5.2.2
