### ISSUE TITLE
Debug test fails without error message

### ISSUE THREAD

**Issue by wmertens** [kavod-io/vscode-jest-test-adapter#47]
I'm trying to debug a single test, and it's failing to start.

I found some error messages in `Log (Window)`:
```
[2020-04-28 10:26:08.750] [renderer1] [error] Unexpected token (135:16): SyntaxError: Unexpected token (135:16)
	at t.J.raise (/home/wmertens/.vscode-server/extensions/orta.vscode-jest-3.1.1/out/extension.js:369:181235)
	at t.U.unexpected (/home/wmertens/.vscode-server/extensions/orta.vscode-jest-3.1.1/out/extension.js:369:134462)
	at t.G.parseExprAtom (/home/wmertens/.vscode-server/extensions/orta.vscode-jest-3.1.1/out/extension.js:369:169738)
	at t.parseExprAtom (/home/wmertens/.vscode-server/extensions/orta.vscode-jest-3.1.1/out/extension.js:370:23978)
	at t.G.parseExprSubscripts (/home/wmertens/.vscode-server/extensions/orta.vscode-jest-3.1.1/out/extension.js:369:164643)
	at t.G.parseMaybeUnary (/home/wmertens/.vscode-server/extensions/orta.vscode-jest-3.1.1/out/extension.js:369:164227)
	at t.G.parseExprOps (/home/wmertens/.vscode-server/extensions/orta.vscode-jest-3.1.1/out/extension.js:369:162801)
	at t.G.parseMaybeConditional (/home/wmertens/.vscode-server/extensions/orta.vscode-jest-3.1.1/out/extension.js:369:162394)
	at t.G.parseMaybeAssign (/home/wmertens/.vscode-server/extensions/orta.vscode-jest-3.1.1/out/extension.js:369:161615)
	at t.parseMaybeAssign (/home/wmertens/.vscode-server/extensions/orta.vscode-jest-3.1.1/out/extension.js:370:23184)
	at t.G.parseConditional (/home/wmertens/.vscode-server/extensions/orta.vscode-jest-3.1.1/out/extension.js:369:162590)
	at t.parseConditional (/home/wmertens/.vscode-server/extensions/orta.vscode-jest-3.1.1/out/extension.js:370:15312)
	at t.G.parseMaybeConditional (/home/wmertens/.vscode-server/extensions/orta.vscode-jest-3.1.1/out/extension.js:369:162437)
	at t.G.parseMaybeAssign (/home/wmertens/.vscode-server/extensions/orta.vscode-jest-3.1.1/out/extension.js:369:161615)
	at t.parseMaybeAssign (/home/wmertens/.vscode-server/extensions/orta.vscode-jest-3.1.1/out/extension.js:370:23184)
	at t.G.parseExpression (/home/wmertens/.vscode-server/extensions/orta.vscode-jest-3.1.1/out/extension.js:369:161028)
	at t.G.parseParenExpression (/home/wmertens/.vscode-server/extensions/orta.vscode-jest-3.1.1/out/extension.js:369:170523)
	at t.V.parseIfStatement (/home/wmertens/.vscode-server/extensions/orta.vscode-jest-3.1.1/out/extension.js:369:139499)
...
```

* It seems to me that the error message is missing some information, like which file it was parsing.
* would it be possible to build the extension using `semicolons:false` so that it inserts line breaks into the generated script? That makes it easier to add debug statements
* note that the test runs fine when I run jest from the command line

**Comment by wmertens** [comment]
🤦 I see that these error messages are for the Orta Jest extension.

I tried disabling it but it makes no difference. I click "debug", it switches to the debugger, never shows anything and then just stops. Any way to debug?

**Comment by wmertens** [comment]
Ah - when I put a breakpoint in the test, it works, and the output is in the debug console. So it would be cool if clicking "debug" adds a breakpoint to the test and switches to the debug console.

Perhaps you already do that and the source mapping isn't working properly?

**Comment by rossknudsen** [comment]
Hey @wmertens thanks for having a look at that for me. TBH I'm not surprised that the debugging isn't working correctly ATM. I've been making quite a few changes elsewhere and I have wondered whether the debugging would continue to work.

Regarding the source maps, I have wondered whether they should even be included in the published extension at all.  I was planning on asking a StackOverflow question about it - if you wanted to do the research, that would be welcome.

Also if you wanted to, its fairly easy to debug from the extension source.  I would love the documentation to include the necessary steps for those who want to improve the extension.  Here are the steps that are required - off the top of my head:

1. clone the source.
2. uninstall the extension if installed (I wonder if you can get away with only disabling it).
3. open the source in VS Code.
4. start debugging (press F5).
5. a new instance of VS Code should launch with the local extension installed (can take a few seconds to warm up).  Normal debugging should be available from the first VS Code instance.

This would be my preferred debugging process - although I am interested in what you can achieve with the source maps themselves.  If you do try them, I'm happy to take a PR to update the documentation and if you discover bugs related to the test debugging, I'm happy to take PRs for that too 😄 .

**Comment by rossknudsen** [comment]
Hmmm, I reread your last comment.  I think that dynamically adding the breakpoints in the tests would be difficult to achieve.  If you wanted to take a look at it yourself, I'm happy to take PRs.  You would want to look in `adapter.ts#debug()`.  You would want to check what you were passed to the method to determine whether you can add appropriate breakpoints.

In the meantime, I'm going to close this ticket.

**Comment by wmertens** [comment]
Perhaps you can add a debugger statement including a comment to step into the next call, which runs the test?
